
#ifndef _MP_SOLVER_TH_H_
#define _MP_SOLVER_TH_H_

#include <windows.h>
#include <stdio.h>
#include <stdlib.h>

#include "../Helper/error_handling.h"
#include "../Helper/Struct.h"

#include "mp_logger.h"
#include "mp_progress_disp.h"
#include "mp_consts.h"
#include "mp_thread_wrapper.h"


/**
 * One solver task describing a search zone and GA configuration.
 *
 * Tasks are generated by :c:func:`make_task_list`, pushed into
 * :c:type:`task_queue_t`, and consumed by solver threads.
 */
struct task_param_s {
	/** Task kind, such as ``GA_TASK`` or ``TERMINATE_THREAD``. */
	int task_type;
	/** Monotonic task identifier assigned by the task queue. */
	uint32_t task_id;
	/** Per-gene lower bounds for double-valued search zones. */
	double* lower;
	/** Per-gene upper bounds for double-valued search zones. */
	double* upper;
	/** Per-gene integer masks for integer-valued search zones. */
	uint32_t* zone_mask;
	/** Per-gene integer zone prefixes for integer-valued search zones. */
	uint32_t* zone_id;
	//double* paramset;
	/** Genetic algorithm configuration copied into the task. */
	config_ga_t config_ga;
};

typedef struct task_param_s task_param_t;


/**
 * Ring buffer of solver tasks shared by task-generation and solver threads.
 */
struct task_queue_s {
	/** Number of task slots in the ring buffer. */
	uint32_t queue_size;
	/** Next task id assigned by :c:func:`add_task`. */
	uint32_t current_task_id;
	/** Solver thread handles owned by the queue. */
	thread_t* thread_id;
	/** Result queue used by tasks consumed from this queue. */
	task_result_queue_t* task_result_queue;
	/** Ring-buffer storage for solver tasks. */
	task_param_t* task_list;
	/** Read cursor in ``task_list``. */
	uint32_t first_task_id;
	/** Write cursor in ``task_list``. */
	uint32_t next_task_id;
	/** Mutex protecting queue cursors and storage. */
	thread_mutex_t* lock;
};

typedef struct task_queue_s task_queue_t;

/**
 * One fitness-evaluation subtask for a slice of individuals.
 */
struct fx_task_param_s {
	/** Task kind, such as ``FX_TASK`` or ``TERMINATE_THREAD``. */
	int task_type;
	/** Identifier for this fitness subtask. */
	uint32_t task_id;
	/** First sorted-individual position to evaluate. */
	uint32_t individual_min;
	/** Last sorted-individual position to evaluate, inclusive. */
	uint32_t individual_max;
	/** Gene pool containing individuals and result buffers. */
	gene_pool_t* gene_pool;
	/** Parent solver task containing bounds and objective configuration. */
	task_param_t* task_param;
};

typedef struct fx_task_param_s fx_task_param_t;

/**
 * Ring buffer for parallel fitness-evaluation subtasks.
 */
struct fx_task_queue_s {
	/** Read cursor in ``fx_task_list``. */
	uint32_t first_task_id;
	/** Write cursor in ``fx_task_list``. */
	uint32_t next_task_id;
	/** Number of individuals assigned to each fitness subtask. */
	uint32_t task_size_fx;
	/** Number of task slots in the ring buffer. */
	uint32_t queue_size;
	/** Fitness worker thread handles owned by the queue. */
	thread_t* thread_id;
	/** Ring-buffer storage for fitness subtasks. */
	fx_task_param_t* fx_task_list;
	/** Mutex protecting queue cursors and storage. */
	thread_mutex_t* lock;
};

typedef struct fx_task_queue_s fx_task_queue_t;


/**
 * Context handed to a solver thread.
 *
 * It connects the solver task queue, optional fitness task queue, and runtime
 * settings needed for one worker loop.
 */
struct thread_param_s {
	/** Worker status flag used by the solver loop. */
	int status;
	/** Shared solver task queue. */
	task_queue_t* task_queue;
	/** Shared fitness task queue. */
	fx_task_queue_t* fx_task_queue;
	/** Runtime settings copied into the worker context. */
	runtime_param_t runtime_param;
};

typedef struct thread_param_s thread_param_t;


/**
 * Initialize the solver task queue.
 *
 * :param task_queue: Queue struct to initialize.
 * :param queue_size: Number of task slots in the ring buffer.
 * :param task_result_queue: Result queue that solver tasks report into.
 * :param thread_count: Number of solver-thread handles to allocate.
 */
void init_task_queue(task_queue_t* task_queue, uint32_t queue_size, task_result_queue_t* task_result_queue, uint32_t thread_count);

/**
 * Release solver task queue storage and synchronization primitives.
 *
 * :param task_queue: Queue initialized by :c:func:`init_task_queue`.
 */
void free_task_queue(task_queue_t* task_queue);

/**
 * Allocate per-task bounds and zone masks.
 *
 * :param runtime_param: Runtime dimensions used for array sizing.
 * :param config_ga: Configuration copied into the task.
 * :param task: Task struct to initialize.
 */
void init_task(runtime_param_t runtime_param, config_ga_t config_ga, task_param_t* task);

/**
 * Release per-task bounds and zone arrays.
 *
 * :param task: Task initialized by :c:func:`init_task`.
 */
void free_task(task_param_t* task);

/**
 * Push a solver task into the queue, blocking while the ring buffer is full.
 *
 * :param task_queue: Destination solver queue.
 * :param task: Task to enqueue by value.
 */
void add_task(task_queue_t* task_queue, task_param_t* task);

/**
 * Pop a solver task from the queue, blocking while the ring buffer is empty.
 *
 * :param task_queue: Source solver queue.
 * :param task: Destination task record.
 */
void get_task(task_queue_t* task_queue, task_param_t* task);

/**
 * Queue termination tasks and join all solver threads.
 *
 * :param task_queue: Solver queue whose worker threads should stop.
 * :param thread_count: Number of solver workers to stop.
 */
void stop_task_solver_threads(task_queue_t* task_queue, uint32_t thread_count);

/**
 * Initialize the fitness-task queue.
 *
 * :param fx_task_queue: Queue struct to initialize.
 * :param queue_size: Number of fitness-task slots.
 * :param thread_count: Number of fitness-worker handles to allocate.
 * :param fx_task_count: Number of individuals per queued fitness subtask.
 */
void init_fx_task_queue(fx_task_queue_t* fx_task_queue, uint32_t queue_size, uint32_t thread_count, uint32_t fx_task_count);

/**
 * Release fitness-task queue storage and synchronization primitives.
 *
 * :param fx_task_queue: Queue initialized by :c:func:`init_fx_task_queue`.
 */
void free_fx_task_queue(fx_task_queue_t* fx_task_queue);

/**
 * Push a fitness-evaluation subtask, blocking while the queue is full.
 *
 * :param fx_task_queue: Destination fitness queue.
 * :param fx_task: Fitness subtask to enqueue by value.
 */
void add_fx_task(fx_task_queue_t* fx_task_queue, fx_task_param_t fx_task);

/**
 * Pop a fitness-evaluation subtask, blocking while the queue is empty.
 *
 * :param fx_task_queue: Source fitness queue.
 * :param fx_task: Destination fitness subtask.
 */
void get_fx_task(fx_task_queue_t* fx_task_queue, fx_task_param_t* fx_task);

/**
 * Queue termination tasks and join all fitness-worker threads.
 *
 * :param task_queue: Fitness queue whose worker threads should stop.
 * :param thread_count: Number of fitness workers to stop.
 */
void stop_fx_task_threads(fx_task_queue_t* task_queue, uint32_t thread_count);


#endif // _MP_SOLVER_TH_H_



